export const tournamentSources = [
  {
    name: 'FIFA World Cup',
    year: 1930,
    host: 'Uruguay',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1930/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1934,
    host: 'Italy',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1934/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1938,
    host: 'France',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1938/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1950,
    host: 'Brazil',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1950/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1954,
    host: 'Switzerland',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1954/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1958,
    host: 'Sweden',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1958/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1962,
    host: 'Chile',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1962/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1966,
    host: 'England',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1966/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1970,
    host: 'Mexico',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1970/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1974,
    host: 'West Germany',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1974/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1978,
    host: 'Argentina',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1978/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1982,
    host: 'Spain',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1982/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1986,
    host: 'Mexico',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1986/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1990,
    host: 'Italy',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1990/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1994,
    host: 'United States',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1994/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 1998,
    host: 'France',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/1998/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2002,
    host: 'South Korea, Japan',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2002/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2006,
    host: 'Germany',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2006/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2010,
    host: 'South Africa',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2010/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2014,
    host: 'Brazil',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2014/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2018,
    host: 'Russia',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2018/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2022,
    host: 'Qatar',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2022/worldcup-full.json',
  },
  {
    name: 'FIFA World Cup',
    year: 2026,
    host: 'Canada, United States, Mexico',
    url: 'https://raw.githubusercontent.com/openfootball/worldcup.json/refs/heads/master/2026/worldcup-full.json',
  },
];
